import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-gray-900`}>
        <main className="h-full relative">
          <Navbar />
          <section className="flex border border-red-600 min-h-screen px-1 pb-1 pt-36 max-md:pb-14 sm:px-14">
            <div className=" w-full max-w-5xl">{children}</div>
          </section>
        </main>
      </body>
    </html>
  );
}
