// data/newsData.ts
export const newsData = [
  {
    id: 1,
    title: 'Breaking News: Major Transfer Announced',
    content: 'Details about a major transfer in the football world.',
  },
  {
    id: 2,
    title: 'Match Review: Highlights and Analysis',
    content:
      'A review of the latest football matches with highlights and analysis.',
  },
  {
    id: 3,
    title: 'Injury Report: Key Players Missing',
    content: 'An update on the injured players for the upcoming matches.',
  },
  {
    id: 4,
    title: 'Upcoming Fixtures: What to Watch',
    content: 'A preview of the upcoming fixtures and what to watch.',
  },
  {
    id: 5,
    title: 'Team Tactics: How Teams Are Shaping Up',
    content: 'An analysis of the tactical setups of various teams.',
  },
];


// data/teamsData.ts
export const teamsData = [
  { id: 1, name: 'Manchester United', league: 'Premier League' },
  { id: 2, name: 'Real Madrid', league: 'La Liga' },
  { id: 3, name: 'FC Barcelona', league: 'La Liga' },
  { id: 4, name: 'Bayern Munich', league: 'Bundesliga' },
  { id: 5, name: 'Liverpool', league: 'Premier League' },
  { id: 6, name: 'Paris Saint-Germain', league: 'Ligue 1' },
  { id: 7, name: 'Juventus', league: 'Serie A' },
  { id: 8, name: 'Chelsea', league: 'Premier League' },
  { id: 9, name: 'Manchester City', league: 'Premier League' },
  { id: 10, name: 'Arsenal', league: 'Premier League' },
  { id: 11, name: 'AC Milan', league: 'Serie A' },
  { id: 12, name: 'Inter Milan', league: 'Serie A' },
  { id: 13, name: 'Tottenham Hotspur', league: 'Premier League' },
  { id: 14, name: 'Borussia Dortmund', league: 'Bundesliga' },
  { id: 15, name: 'Atletico Madrid', league: 'La Liga' },
  { id: 16, name: 'AS Roma', league: 'Serie A' },
  { id: 17, name: 'Napoli', league: 'Serie A' },
  { id: 18, name: 'Lazio', league: 'Serie A' },
  { id: 19, name: 'Ajax', league: 'Eredivisie' },
  { id: 20, name: 'Benfica', league: 'Primeira Liga' },
  { id: 21, name: 'Porto', league: 'Primeira Liga' },
  { id: 22, name: 'Sporting CP', league: 'Primeira Liga' },
  { id: 23, name: 'Marseille', league: 'Ligue 1' },
  { id: 24, name: 'Olympique Lyonnais', league: 'Ligue 1' },
  { id: 25, name: 'Sevilla', league: 'La Liga' },
  { id: 26, name: 'Valencia', league: 'La Liga' },
  { id: 27, name: 'Villarreal', league: 'La Liga' },
  { id: 28, name: 'RB Leipzig', league: 'Bundesliga' },
  { id: 29, name: 'Bayer Leverkusen', league: 'Bundesliga' },
  { id: 30, name: 'Schalke 04', league: 'Bundesliga' },
  { id: 31, name: 'Galatasaray', league: 'Süper Lig' },
  { id: 32, name: 'Fenerbahçe', league: 'Süper Lig' },
  { id: 33, name: 'Besiktas', league: 'Süper Lig' },
  { id: 34, name: 'Celtic', league: 'Scottish Premiership' },
  { id: 35, name: 'Rangers', league: 'Scottish Premiership' },
  { id: 36, name: 'Shakhtar Donetsk', league: 'Ukrainian Premier League' },
  { id: 37, name: 'Dynamo Kyiv', league: 'Ukrainian Premier League' },
  { id: 38, name: 'Zenit Saint Petersburg', league: 'Russian Premier League' },
  { id: 39, name: 'CSKA Moscow', league: 'Russian Premier League' },
  { id: 40, name: 'Lokomotiv Moscow', league: 'Russian Premier League' },
  { id: 41, name: 'Spartak Moscow', league: 'Russian Premier League' },
  { id: 42, name: 'Anderlecht', league: 'Belgian Pro League' },
  { id: 43, name: 'Club Brugge', league: 'Belgian Pro League' },
  { id: 44, name: 'Genk', league: 'Belgian Pro League' },
  { id: 45, name: 'Standard Liège', league: 'Belgian Pro League' },
  { id: 46, name: 'PSV Eindhoven', league: 'Eredivisie' },
  { id: 47, name: 'Feyenoord', league: 'Eredivisie' },
  { id: 48, name: 'AZ Alkmaar', league: 'Eredivisie' },
  { id: 49, name: 'RB Salzburg', league: 'Austrian Bundesliga' },
  { id: 50, name: 'FC Basel', league: 'Swiss Super League' },
];
